spring:
  application:
    name: JobCoordi

  datasource:
    url: jdbc:mysql://localhost:3306/job_coordi
    username: min3
    password: min3

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

